### ISSUE TITLE
MySQL Option

### ISSUE THREAD

**Issue by Petahhh** [scholarsportal/SwiftBulkUploader#9]
Sqlite does not seem powerful enough to handle uploading of directories with 20+ million files. An option to use a MySQL database, perhaps as a flag, will be helpful for users with this resources and this need.

**Comment by cudevmaxwell** [comment]
I wouldn't agree, http://www.sqlite.org/limits.html. Even if every file path entry is 10 KB on disk (very long paths!) the DB would be 200GB, which is well under the limit for SQLite. 

However, if there's interest, I can replace the raw SQL calls <del>in my PR</del> and instead use sqlalchemy. Then anyone could use any db they wanted.

**Comment by Petahhh** [comment]
Thanks for the feedback.  The option to use any database you want would be really convenient.

Currently, I've been unable to upload a directory with 17 million files. I repeatedly get a "Database Error: disk I/O error."

**Comment by cudevmaxwell** [comment]
How much free space is on the drive?

**Comment by Petahhh** [comment]
About 200GB

**Comment by cudevmaxwell** [comment]
I'll try to reproduce.

Edit: Creating many, many small files.

Edit 2: At 2 of 20 million.

Edit 3: At 9 of 20 million.

**Comment by cudevmaxwell** [comment]
Created over 22 million test objects, here's some numbers:

```
$ time swiftbulkuploader --db=/tmp/test.db prepare ~/development/test_manyfiles/

real    48m7.618s
user    13m54.523s
sys     19m42.090s

$ time swiftbulkuploader --db=/tmp/test.db count
Stored accessible file paths: 22159415
  Not Uploaded: 22159415
      Uploaded: 0
  Upload Error: 0
Inaccessible file paths: 0
Inaccessible directory paths: 0

real    1m47.469s
user    0m25.491s
sys     0m24.902s

```

So, very sluggish. I'll run the upload command over the weekend. Good test of the tool, and also a good test of the beta cluster.

**Comment by cudevmaxwell** [comment]
Now that I think about it, is > 22 million inserts in 50 minutes that slow? That's over 7000 inserts per second.

**Comment by cudevmaxwell** [comment]
@Petahhh, did the error come up in the prepare step, or the upload step?

**Comment by cudevmaxwell** [comment]
Stopping the upload command now. Got to ~140,000 files in 5 hours, which is too slow. No errors from SQLite, though.

**Comment by Petahhh** [comment]
I got the I/O error during the prepare step

**Comment by cudevmaxwell** [comment]
Working on this today.

**Comment by cudevmaxwell** [comment]
Got something here: https://github.com/cudevmaxwell/SwiftBulkUploader/tree/feature-useSQLAlchemy I'll issue a PR when it's ready and I've made sure it's working well with both sqlite and mysql.

**Comment by Petahhh** [comment]
This looks great! Thanks @cudevmaxwell ! Excited to test it out =)
